[package]
name = "yoshino-prelude"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yoshino-core= {path= "../core"}
yoshino-derive= {path= "../derive"}
